import React, { useEffect, useState } from "react";

type Med={id:string;name:string;dosage:string;frequency?:string;times?:string[];instructions?:string;active?:boolean};
type Event={id:string;medicationId:string;taken:boolean;takenAt:string};

export default function MedicationManager(){
 const [medications,setMedications]=useState<Med[]>([]),[events,setEvents]=useState<Record<string,Event[]>>({}),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch("/api/medications/me",{credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load medications.");const meds=d.medications||[];setMedications(meds);const pairs=await Promise.all(meds.map(async(m:Med)=>{const er=await fetch("/api/medications/adherence?medicationId="+encodeURIComponent(m.id),{credentials:"include"});if(!er.ok)return [m.id,[]] as const;const ed=await er.json();return [m.id,ed.events||[]] as const;}));setEvents(Object.fromEntries(pairs));}catch(e){setError(e instanceof Error?e.message:"Unable to load medications.");}finally{setLoading(false);}};
 useEffect(()=>{void load()},[]);
 const record=async(medicationId:string,taken:boolean)=>{const r=await fetch("/api/medications/adherence",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({medicationId,taken})});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||"Unable to record medication status.");return;}await load();};
 if(loading)return <div className="p-6 text-center">Loading your medications…</div>;
 const active=medications.filter(m=>m.active!==false);
 return <div className="max-w-5xl mx-auto p-6 space-y-5"><div><h2 className="text-2xl font-bold">💊 Medication Manager</h2><p className="text-gray-600">Your prescribed medications and recorded adherence.</p></div>{error&&<div className="p-3 bg-red-50 text-red-700 rounded">{error}</div>}<div className="p-4 border rounded-xl bg-amber-50 text-amber-900 text-sm">Medication interaction checking is not enabled. Do not rely on this screen for interaction or dosing decisions; consult a qualified clinician or pharmacist.</div>{!active.length?<div className="p-8 bg-white rounded-xl border text-center text-gray-500">No active medications found.</div>:<div className="grid gap-4 md:grid-cols-2">{active.map(m=>{const recent=(events[m.id]||[]).slice(0,10);return <div key={m.id} className="bg-white rounded-xl border p-5 space-y-3"><div className="flex justify-between gap-3"><b>{m.name}</b><span>{m.dosage}</span></div>{m.frequency&&<p className="text-gray-600">{m.frequency}</p>}{m.times?.length?<p className="text-sm text-gray-500">Scheduled: {m.times.join(", ")}</p>:null}{m.instructions&&<p className="p-3 bg-gray-50 rounded text-sm">{m.instructions}</p>}<div className="text-sm text-gray-600">Recent recorded doses: {recent.filter(e=>e.taken).length} taken / {recent.length} logged</div><div className="flex gap-2"><button onClick={()=>record(m.id,true)} className="flex-1 px-3 py-2 rounded bg-green-600 text-white">Taken</button><button onClick={()=>record(m.id,false)} className="flex-1 px-3 py-2 rounded bg-gray-200">Missed</button></div></div>})}</div>}</div>;
}