import { getDb } from '../_lib/mongo';
import { json, methodNotAllowed } from '../_lib/response';
import { requireRole } from '../_lib/authz';
import { audit } from '../_lib/audit';
const clean=(v:unknown,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
export async function GET(request:Request):Promise<Response>{const a=requireRole(request,['patient','admin']);if(a instanceof Response)return a;const db=await getDb();const claims=await db.collection('insurance_claims').find(a.userType==='patient'?{patientId:a.userId}:{}).sort({createdAt:-1}).limit(100).toArray();return json({claims});}
export async function POST(request:Request):Promise<Response>{const a=requireRole(request,['patient']);if(a instanceof Response)return a;try{const b=await request.json();const treatmentType=clean(b?.treatmentType,120),hospitalName=clean(b?.hospitalName,200),billAmount=Number(b?.billAmount),treatmentDate=clean(b?.treatmentDate,30);if(!treatmentType||!hospitalName||!treatmentDate||!Number.isFinite(billAmount)||billAmount<=0)return json({error:'Invalid claim.'},{status:400});const claim={claimId:'CLM-'+crypto.randomUUID().slice(0,8).toUpperCase(),patientId:a.userId,treatmentType,hospitalName,treatmentDate,billAmount,documents:Array.isArray(b?.documents)?b.documents.filter((x:unknown)=>typeof x==='string').slice(0,5):[],status:'SUBMITTED',createdAt:new Date(),updatedAt:new Date()};const db=await getDb();await db.collection('insurance_claims').insertOne(claim);await audit({actorId:a.userId,actorRole:'patient',action:'insurance.claim.create',resource:claim.claimId,outcome:'success'});return json({success:true,claim},{status:201});}catch{return json({error:'Unable to submit claim.'},{status:500})}}
export async function PATCH(request:Request):Promise<Response>{const a=requireRole(request,['admin']);if(a instanceof Response)return a;try{const b=await request.json();if(typeof b?.claimId!=='string')return json({error:'Claim id required.'},{status:400});const updates:Record<string,unknown>={updatedAt:new Date()};if(typeof b.status==='string'&&['SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','SETTLED'].includes(b.status))updates.status=b.status;if(Number.isFinite(b.approvedAmount)&&b.approvedAmount>=0)updates.approvedAmount=b.approvedAmount;const db=await getDb();const r=await db.collection('insurance_claims').updateOne({claimId:b.claimId},{$set:updates});if(!r.matchedCount)return json({error:'Claim not found.'},{status:404});await audit({actorId:a.userId,actorRole:'admin',action:'insurance.claim.update',resource:b.claimId,outcome:'success'});return json({success:true});}catch{return json({error:'Unable to update claim.'},{status:500})}}
export function PUT(){return methodNotAllowed(['GET','POST','PATCH']);} export function DELETE(){return methodNotAllowed(['GET','POST','PATCH']);}
