import { getDb } from '../_lib/mongo.js';
import { json, methodNotAllowed } from '../_lib/response.js';
import { requireRole } from '../_lib/authz.js';
import { audit } from '../_lib/audit.js';
const clean=(v:unknown,max=100)=>typeof v==='string'?v.trim().slice(0,max):'';
export async function GET(request:Request):Promise<Response>{const a=requireRole(request,['patient','doctor','admin']);if(a instanceof Response)return a;const db=await getDb();const filter=a.userType==='patient'?{patientId:a.userId}:a.userType==='doctor'?{doctorId:a.userId}:{};const sessions=await db.collection('telemedicine_sessions').find(filter).sort({scheduledTime:1}).limit(100).toArray();return json({sessions});}
export async function POST(request:Request):Promise<Response>{const a=requireRole(request,['patient','doctor','admin']);if(a instanceof Response)return a;try{const b=await request.json();const patientId=clean(b?.patientId)|| (a.userType==='patient'?a.userId:''),doctorId=clean(b?.doctorId)|| (a.userType==='doctor'?a.userId:''),sessionType=clean(b?.sessionType,20);const scheduledTime=new Date(b?.scheduledTime);if(!patientId||!doctorId||Number.isNaN(scheduledTime.getTime())||!['VIDEO','AUDIO','CHAT'].includes(sessionType))return json({error:'Invalid telemedicine session.'},{status:400});if(a.userType==='patient'&&patientId!==a.userId)return json({error:'Forbidden.'},{status:403});if(a.userType==='doctor'&&doctorId!==a.userId)return json({error:'Forbidden.'},{status:403});const session={sessionId:'TEL-'+crypto.randomUUID().slice(0,8).toUpperCase(),patientId,doctorId,sessionType,scheduledTime,status:'SCHEDULED',meetingUrl:undefined,createdBy:a.userId,createdAt:new Date(),updatedAt:new Date()};const db=await getDb();await db.collection('telemedicine_sessions').insertOne(session);await audit({actorId:a.userId,actorRole:a.userType,action:'telemedicine.create',resource:session.sessionId,outcome:'success'});return json({success:true,session},{status:201});}catch{return json({error:'Unable to schedule telemedicine session.'},{status:500})}}
export async function PATCH(request:Request):Promise<Response>{const a=requireRole(request,['patient','doctor','admin']);if(a instanceof Response)return a;try{const b=await request.json();if(typeof b?.sessionId!=='string')return json({error:'Session id required.'},{status:400});const db=await getDb();const s=await db.collection('telemedicine_sessions').findOne({sessionId:b.sessionId});if(!s)return json({error:'Session not found.'},{status:404});if(a.userType!=='admin'&&s.patientId!==a.userId&&s.doctorId!==a.userId)return json({error:'Forbidden.'},{status:403});const updates:Record<string,unknown>={updatedAt:new Date()};if(typeof b.status==='string'&&['SCHEDULED','ACTIVE','COMPLETED','CANCELLED'].includes(b.status))updates.status=b.status;if(typeof b.meetingUrl==='string'&&a.userType==='admin')updates.meetingUrl=b.meetingUrl.slice(0,1000);await db.collection('telemedicine_sessions').updateOne({sessionId:b.sessionId},{$set:updates});await audit({actorId:a.userId,actorRole:a.userType,action:'telemedicine.update',resource:b.sessionId,outcome:'success'});return json({success:true});}catch{return json({error:'Unable to update session.'},{status:500})}}
export function PUT(){return methodNotAllowed(['GET','POST','PATCH']);} export function DELETE(){return methodNotAllowed(['GET','POST','PATCH']);}
